//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupQuestionnaireApp.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupCompletedPackage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupCompletedPackage()
        {
            this.GroupCompletedActivities = new HashSet<GroupCompletedActivity>();
        }
    
        public int CompletedPackageID { get; set; }
        public int GroupID { get; set; }
        public int PackageType { get; set; }
        public System.DateTime CompletionDate { get; set; }
        public int SessionNumber { get; set; }
        public int ClientID { get; set; }
        public int IntakeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupCompletedActivity> GroupCompletedActivities { get; set; }
    }
}
