//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupQuestionnaireApp.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupActivityQuestion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupActivityQuestion()
        {
            this.GroupActivityOptions = new HashSet<GroupActivityOption>();
            this.GroupActivityTexts = new HashSet<GroupActivityText>();
        }
    
        public string QuestionnaireType { get; set; }
        public string QuestionID { get; set; }
        public int DisplayOrder { get; set; }
        public string QuestionType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupActivityOption> GroupActivityOptions { get; set; }
        public virtual GroupActivityType GroupActivityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupActivityText> GroupActivityTexts { get; set; }
    }
}
