//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupPackageApp.Resources.Home.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroupPackageApp.Resources.Home.Views.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date is required.
        /// </summary>
        public static string BirthDateInvalid {
            get {
                return ResourceManager.GetString("BirthDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date is required.
        /// </summary>
        public static string BirthDateRequired {
            get {
                return ResourceManager.GetString("BirthDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Year must be less than the current year.
        /// </summary>
        public static string BirthYearInvalid {
            get {
                return ResourceManager.GetString("BirthYearInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth year must be greater than 1900.
        /// </summary>
        public static string BirthYearInvalid2 {
            get {
                return ResourceManager.GetString("BirthYearInvalid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Desk Override.
        /// </summary>
        public static string BtnClientOverride {
            get {
                return ResourceManager.GetString("BtnClientOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not sure.
        /// </summary>
        public static string BtnNotSure {
            get {
                return ResourceManager.GetString("BtnNotSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string BtnRestartTests {
            get {
                return ResourceManager.GetString("BtnRestartTests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input is required.
        /// </summary>
        public static string ChallengeResponseInvalid {
            get {
                return ResourceManager.GetString("ChallengeResponseInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client ID is required.
        /// </summary>
        public static string ClientID {
            get {
                return ResourceManager.GetString("ClientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couple.
        /// </summary>
        public static string Couple {
            get {
                return ResourceManager.GetString("Couple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        public static string Family {
            get {
                return ResourceManager.GetString("Family", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        public static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intake ID is required.
        /// </summary>
        public static string IntakeID {
            get {
                return ResourceManager.GetString("IntakeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a language to continue.
        /// </summary>
        public static string LanguageSelectionRequired {
            get {
                return ResourceManager.GetString("LanguageSelectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max length is {0} characters.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!  Looks like you may require some assistance.  Please see the front desk and ask them to enter the following information. If you ended up here by mistake, click the logo to go back to the language selection page. .
        /// </summary>
        public static string PageDescriptionClientOverride {
            get {
                return ResourceManager.GetString("PageDescriptionClientOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are able to provide some tests in the language of your choice. If your preferred language isn&apos;t available, we may be able to provide paper tests.  In this case, please see the front desk for assistance. .
        /// </summary>
        public static string PageDescriptionLanguageSelect {
            get {
                return ResourceManager.GetString("PageDescriptionLanguageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops!  Looks like you may require some assistance.  Please see the front desk and ask them for assistance. If you ended up here by mistake, click the &quot;Restart&quot; button to return to restart the validation process..
        /// </summary>
        public static string PageDescriptionRestart {
            get {
                return ResourceManager.GetString("PageDescriptionRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It appears that you may be here for more than one type of counselling or that you are seeing two or more different counsellors.  If this is the case, please select the counsellor and the type of counselling you are here for today.  If you aren&apos;t sure, or your counsellor isn&apos;t listed here, please select &quot;I&apos;m not sure&quot; and ask the front desk for assistance.   .
        /// </summary>
        public static string PageDescriptionSelectCounsellor {
            get {
                return ResourceManager.GetString("PageDescriptionSelectCounsellor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please indicate whether you have already completed your counselling for today or not..
        /// </summary>
        public static string PageDescriptionSelectPrePostSessionTest {
            get {
                return ResourceManager.GetString("PageDescriptionSelectPrePostSessionTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before we can continue, we need to know a little bit about you.  This information will help us identify you and allow us to link your counselling session to your client profile. &lt;strong&gt;Please enter the information you provided when you registered for counselling. &lt;/strong&gt; If you have any problems or your information has changed, please see the front desk..
        /// </summary>
        public static string PageDescriptionValidateClient {
            get {
                return ResourceManager.GetString("PageDescriptionValidateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Desk Override.
        /// </summary>
        public static string PageTitleClientOverride {
            get {
                return ResourceManager.GetString("PageTitleClientOverride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language Selection.
        /// </summary>
        public static string PageTitleLanguageSelect {
            get {
                return ResourceManager.GetString("PageTitleLanguageSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        public static string PageTitleRestart {
            get {
                return ResourceManager.GetString("PageTitleRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Validate Information.
        /// </summary>
        public static string PageTitleSecondaryValidation {
            get {
                return ResourceManager.GetString("PageTitleSecondaryValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Counsellor.
        /// </summary>
        public static string PageTitleSelectCounsellor {
            get {
                return ResourceManager.GetString("PageTitleSelectCounsellor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you already completed your counselling session today?.
        /// </summary>
        public static string PageTitleSelectPrePostSession {
            get {
                return ResourceManager.GetString("PageTitleSelectPrePostSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1: Enter Information.
        /// </summary>
        public static string PageTitleValidateClient {
            get {
                return ResourceManager.GetString("PageTitleValidateClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occurred while setting language preference.
        /// </summary>
        public static string SelectLanguageError {
            get {
                return ResourceManager.GetString("SelectLanguageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, I have met with my therapist today.
        /// </summary>
        public static string SelectPrePostComplete {
            get {
                return ResourceManager.GetString("SelectPrePostComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select one of the choices.
        /// </summary>
        public static string SelectPrePostError {
            get {
                return ResourceManager.GetString("SelectPrePostError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No, I have not met with my therapist today.
        /// </summary>
        public static string SelectPrePostNotComplete {
            get {
                return ResourceManager.GetString("SelectPrePostNotComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Validate Email.
        /// </summary>
        public static string ValidateEmail {
            get {
                return ResourceManager.GetString("ValidateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to verify your information, please enter the email address that you included with your original request for counselling.  If you do not remember the email address you entered or if you did not provide us with an email address, please see the front desk for assistance. .
        /// </summary>
        public static string ValidateEmailDescription {
            get {
                return ResourceManager.GetString("ValidateEmailDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Validate Phone Number.
        /// </summary>
        public static string ValidatePhoneNumber {
            get {
                return ResourceManager.GetString("ValidatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to verify your information, please enter one of the phone numbers that you included with your original request for counselling.  If you do not remember the phone number you entered or if you did not provide us with a phone number, please see the front desk for assistance. .
        /// </summary>
        public static string ValidatePhoneNumberDescription {
            get {
                return ResourceManager.GetString("ValidatePhoneNumberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2: Validate Postal Code.
        /// </summary>
        public static string ValidatePostalCode {
            get {
                return ResourceManager.GetString("ValidatePostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to verify your information, please enter the postal code that you included with your original request for counselling.  If you do not remember the postal code you entered or if you did not provide us with a postal code, please see the front desk for assistance. .
        /// </summary>
        public static string ValidatePostalCodeDescription {
            get {
                return ResourceManager.GetString("ValidatePostalCodeDescription", resourceCulture);
            }
        }
    }
}
