//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupPackageActivity
    {
        public int GroupPackageActID { get; set; }
        public int PackageType { get; set; }
        public int ProgramID { get; set; }
        public int ActivityDisplayOrder { get; set; }
        public string QuestionnaireType { get; set; }
    
        public virtual GroupActivityType GroupActivityType { get; set; }
        public virtual GroupPackageName GroupPackageName { get; set; }
        public virtual GroupProgram GroupProgram { get; set; }
    }
}
