//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary1
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupCompletedActivity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupCompletedActivity()
        {
            this.GroupActivityAnswers = new HashSet<GroupActivityAnswer>();
            this.GroupActivityTestScores = new HashSet<GroupActivityTestScore>();
        }
    
        public int CompletedActivityID { get; set; }
        public int CompletedPackageID { get; set; }
        public int ActivityType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupActivityAnswer> GroupActivityAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupActivityTestScore> GroupActivityTestScores { get; set; }
        public virtual GroupCompletedPackage GroupCompletedPackage { get; set; }
    }
}
