//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GroupPackageApp.Resources.Test.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GroupPackageApp.Resources.Test.Views.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you were growing up, during your first 18 years of life:.
        /// </summary>
        public static string ACEDescription {
            get {
                return ResourceManager.GetString("ACEDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s my ACE Score?.
        /// </summary>
        public static string ACEQuestionnaireTitle {
            get {
                return ResourceManager.GetString("ACEQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string BtnFinish {
            get {
                return ResourceManager.GetString("BtnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Chart.
        /// </summary>
        public static string BtnOpenChart {
            get {
                return ResourceManager.GetString("BtnOpenChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Kids sometimes have different feelings and ideas.&lt;/p&gt;
        ///&lt;p&gt;This form lists the feelings and ideas in groups. From each group of three sentences, pick &lt;strong&gt;one&lt;/strong&gt; sentence that describes you best for the &lt;strong&gt;past two weeks&lt;/strong&gt;. After you pick a sentence from the first group, go on to the next group.&lt;/p&gt;
        ///&lt;p&gt;There is no right or wrong answer. Just pick a sentence that best describes the way you have been recently. Put a mark in the box next to the sentence that you pick.&lt;/p&gt;
        ///&lt;p&gt;Remember,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CDI2Description {
            get {
                return ResourceManager.GetString("CDI2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CDI-2 Self-Report.
        /// </summary>
        public static string CDI2QuestionnaireTitle {
            get {
                return ResourceManager.GetString("CDI2QuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please assist us in improving our program by answering these questions. We are interested in your honest opinion, whether it is positive or negative. Please answer all of the questions. We also welcome your comments and suggestions. Thank you very much, we really appreciate your help..
        /// </summary>
        public static string CSQ8Description {
            get {
                return ResourceManager.GetString("CSQ8Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Calgary Counselling Centre Client Satisfaction Questionnaire (CSQ-8).
        /// </summary>
        public static string CSQ8QuestionnaireTitle {
            get {
                return ResourceManager.GetString("CSQ8QuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section, you will find 42 statements about the situation in your family before and after your separation. Read each statement carefully and decide how much you agree or disagree with the statement. Make your response by choosing one of the provided answers (&quot;SA&quot;, &quot;A&quot;, &quot;N&quot;, &quot;D&quot;, or &quot;SD&quot;). Choose only one response for each item. Mark an answer for every statement, even if you are not completely sure of your answer..
        /// </summary>
        public static string DAIRDescription {
            get {
                return ResourceManager.GetString("DAIRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DAI-R.
        /// </summary>
        public static string DAIRQuestionnaireTitle {
            get {
                return ResourceManager.GetString("DAIRQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete the following questions..
        /// </summary>
        public static string EDI3Description1 {
            get {
                return ResourceManager.GetString("EDI3Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For each item, decide if the item is true about you &lt;strong&gt;ALWAYS&lt;/strong&gt;, &lt;strong&gt;USUALLY&lt;/strong&gt;, &lt;strong&gt;OFTEN&lt;/strong&gt;, &lt;strong&gt;SOMETIMES&lt;/strong&gt;, &lt;strong&gt;RARELY&lt;/strong&gt;, or &lt;strong&gt;NEVER&lt;/strong&gt;. Choose the letter that appears beneath your answer for each question. Respond to &lt;strong&gt;ALL&lt;/strong&gt; of the items, making sure that you choose the option that is true about you..
        /// </summary>
        public static string EDI3Description2 {
            get {
                return ResourceManager.GetString("EDI3Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDI-3.
        /// </summary>
        public static string EDI3QuestionnaireTitle {
            get {
                return ResourceManager.GetString("EDI3QuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this section, you will find 42 statements about the relationship between yourself and another person. Read each statement carefully and decide how well the statement describes your relationship with this person. Make your response by choosing one of the provided answers (&quot;SA&quot;, &quot;A&quot;, &quot;D&quot;, or &quot;SD&quot;). Choose only one response for each item. Mark an answer for every statement, even if you are not completely sure of your answer..
        /// </summary>
        public static string FAMDescription {
            get {
                return ResourceManager.GetString("FAMDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAM - III: Dyadic Relationship Scale.
        /// </summary>
        public static string FAMQuestionnaireTitle {
            get {
                return ResourceManager.GetString("FAMQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This questionnaire is designed to measure the way you feel about your life and surroundings. It is not a test, so there are no right or wrong answers. Please answer each item as carefully and as accurately as you can by checking the appropriate box..
        /// </summary>
        public static string GCSDescription {
            get {
                return ResourceManager.GetString("GCSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generalized Contentment Scale (GCS).
        /// </summary>
        public static string GCSQuestionnaireTitle {
            get {
                return ResourceManager.GetString("GCSQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This questionnaire is designed to measure the way you feel about the amount of personal stress that you experience. It is not a test, so there are no right or wrong answers. Please answer each item as carefully and as accurately as you can by placing a number beside each one as follows:
        ///&lt;ol&gt;
        ///&lt;li&gt;None of the time&lt;/li&gt;
        ///&lt;li&gt;Very rarely&lt;/li&gt;
        ///&lt;li&gt;A little of the time&lt;/li&gt;
        ///&lt;li&gt;Some of the time&lt;/li&gt;
        ///&lt;li&gt;A good part of the time&lt;/li&gt;
        ///&lt;li&gt;Most of the time&lt;/li&gt;
        ///&lt;li&gt; All of the time&lt;/li&gt;
        ///&lt;/ol&gt;.
        /// </summary>
        public static string ICSDescription {
            get {
                return ResourceManager.GetString("ICSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of Clinical Stress (ICS).
        /// </summary>
        public static string ICSQuestionnaireTitle {
            get {
                return ResourceManager.GetString("ICSQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This questionnaire is designed to measure how you see yourself. It is not a test, so there are no right or wrong answers. Please answer each item as carefully and as accurately as you can by placing a number beside each one as follows:
        ///&lt;ol&gt;
        ///&lt;li&gt;None of the time&lt;/li&gt;
        ///&lt;li&gt;Very rarely&lt;/li&gt;
        ///&lt;li&gt;A little of the time&lt;/li&gt;
        ///&lt;li&gt;Some of the time&lt;/li&gt;
        ///&lt;li&gt;A good part of the time&lt;/li&gt;
        ///&lt;li&gt;Most of the time&lt;/li&gt;
        ///&lt;li&gt; All of the time&lt;/li&gt;
        ///&lt;/ol&gt;.
        /// </summary>
        public static string ISEDescription {
            get {
                return ResourceManager.GetString("ISEDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index of Self-Esteem (ISE).
        /// </summary>
        public static string ISEQuestionnaireTitle {
            get {
                return ResourceManager.GetString("ISEQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This questionnaire is designed to measure the non-physical abuse you have delivered upon your partner. It is not a test, so there are no right or wrong answers. Please answer each item as carefully and as accurately as you can by placing a number beside each one as follow:
        ///&lt;ol&gt;
        ///&lt;li&gt;Never&lt;/li&gt;
        ///&lt;li&gt;Very rarely&lt;/li&gt;
        ///&lt;li&gt;A little of the time&lt;/li&gt;
        ///&lt;li&gt;Some of the time&lt;/li&gt;
        ///&lt;li&gt;A good part of the time&lt;/li&gt;
        ///&lt;li&gt;Very frequently&lt;/li&gt;
        ///&lt;li&gt;All of the time&lt;/li&gt;
        ///&lt;/ol&gt;.
        /// </summary>
        public static string NPAPSDescription {
            get {
                return ResourceManager.GetString("NPAPSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Physical Abuse of Partner Scale (NPAPS).
        /// </summary>
        public static string NPAPSQuestionnaireTitle {
            get {
                return ResourceManager.GetString("NPAPSQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Looking back over the last week&lt;/strong&gt;, help us understand how you have been feeling. Read each item carefully and mark the box which best describes your current situation..
        /// </summary>
        public static string OQDescription {
            get {
                return ResourceManager.GetString("OQDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome Questionnaire (OQ - 45.2).
        /// </summary>
        public static string OutcomeQuestionnaireTitle {
            get {
                return ResourceManager.GetString("OutcomeQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for completing your questionnaires.  Please click the &quot;finish&quot; button below to complete the process.  Once you are done, please return the device to the front desk. .
        /// </summary>
        public static string PageDescriptionResponseComplete {
            get {
                return ResourceManager.GetString("PageDescriptionResponseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your counsellor or the front desk staff should have informed you what questionnaires you should complete before your counselling session today.  If you are unsure, please contact the front desk for assistance.  .
        /// </summary>
        public static string PageDescriptionSelectTest {
            get {
                return ResourceManager.GetString("PageDescriptionSelectTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Test.
        /// </summary>
        public static string PageTitleCompleteTest {
            get {
                return ResourceManager.GetString("PageTitleCompleteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Complete.
        /// </summary>
        public static string PageTitleResponseComplete {
            get {
                return ResourceManager.GetString("PageTitleResponseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Questionnaires.
        /// </summary>
        public static string PageTitleSelectTest {
            get {
                return ResourceManager.GetString("PageTitleSelectTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This questionnaire is designed to measure the physical abuse you have delivered upon your partner. It is not a test, so there are no right or wrong answers. Please answer each item as carefully and as accurately as you can by placing a number beside each one as follows:
        ///&lt;ol&gt;
        ///&lt;li&gt;Never&lt;/li&gt;
        ///&lt;li&gt;Very rarely&lt;/li&gt;
        ///&lt;li&gt;A little of the time&lt;/li&gt;
        ///&lt;li&gt;Some of the time&lt;/li&gt;
        ///&lt;li&gt;A good part of the time&lt;/li&gt;
        ///&lt;li&gt;Very frequently&lt;/li&gt;
        ///&lt;li&gt;All of the time&lt;/li&gt;
        ///&lt;/ol&gt;.
        /// </summary>
        public static string PAPSDescription {
            get {
                return ResourceManager.GetString("PAPSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Abuse of Partner Scale (PAPS).
        /// </summary>
        public static string PAPSQuestionnaireTitle {
            get {
                return ResourceManager.GetString("PAPSQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read each statement and decide whether it is an accurate statement about you.
        ///&lt;ul&gt;
        ///&lt;li&gt;If the statement is &lt;strong&gt;FALSE, NOT AT ALL TRUE&lt;/strong&gt;, choose &lt;strong&gt;F&lt;/strong&gt;.&lt;/li&gt;
        ///&lt;li&gt;If the statement is &lt;strong&gt;SLIGHTLY TRUE&lt;/strong&gt;, choose &lt;strong&gt;ST&lt;/strong&gt;.&lt;/li&gt;
        ///&lt;li&gt;If the statement is &lt;strong&gt;MAINLY TRUE&lt;/strong&gt;, choose &lt;strong&gt;MT&lt;/strong&gt;.&lt;/li&gt;
        ///&lt;li&gt;If the statement is &lt;strong&gt;VERY TRUE&lt;/strong&gt;, choose &lt;strong&gt;VT&lt;/strong&gt;.&lt;/li&gt;
        ///&lt;/ul&gt;
        ///Give &lt;strong&gt;your own opinion&lt;/strong&gt; of yourself. Be sur [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PASDescription {
            get {
                return ResourceManager.GetString("PASDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This questionnaire is designed to measure the non-physical abuse you have experienced in your relationship with your partner. It is not a test, so there are no right or wrong answers. Please answer each item as carefully and as accurately as you can by placing a number beside each one as follows:
        ///&lt;ol&gt;
        ///&lt;li&gt;None of the time&lt;/li&gt;
        ///&lt;li&gt;Very rarely&lt;/li&gt;
        ///&lt;li&gt;A little of the time&lt;/li&gt;
        ///&lt;li&gt;Some of the time&lt;/li&gt;
        ///&lt;li&gt;A good part of the time&lt;/li&gt;
        ///&lt;li&gt;Most of the time&lt;/li&gt;
        ///&lt;li&gt;All of the time&lt;/li&gt;
        ///&lt;/ol&gt;.
        /// </summary>
        public static string PASNPDescription {
            get {
                return ResourceManager.GetString("PASNPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Abuse Scale: Non-Physical (PASNP).
        /// </summary>
        public static string PASNPQuestionnaireTitle {
            get {
                return ResourceManager.GetString("PASNPQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This questionnaire is designed to measure the physical abuse you have experienced in your relationship with your partner. It is not a test, so there are no right or wrong answers. Please answer each item as carefully and as accurately as you can by placing a number beside each one as follows:
        ///&lt;ol&gt;
        ///&lt;li&gt;None of the time&lt;/li&gt;
        ///&lt;li&gt;Very rarely&lt;/li&gt;
        ///&lt;li&gt;A little of the time&lt;/li&gt;
        ///&lt;li&gt;Some of the time&lt;/li&gt;
        ///&lt;li&gt;A good part of the time&lt;/li&gt;
        ///&lt;li&gt;Most of the time&lt;/li&gt;
        ///&lt;li&gt; All of the time&lt;/li&gt;
        ///&lt;/ol&gt;.
        /// </summary>
        public static string PASPHDescription {
            get {
                return ResourceManager.GetString("PASPHDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Abuse Scale: Physical (PASPH).
        /// </summary>
        public static string PASPHQuestionnaireTitle {
            get {
                return ResourceManager.GetString("PASPHQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAS.
        /// </summary>
        public static string PASQuestionnaireTitle {
            get {
                return ResourceManager.GetString("PASQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This questionnaire contains 36 statements. Read each statement carefully. For each statement, please focus on the child you are most concerned about and choose the response that best represents your opinion. Answer all questions about the same child.
        ///&lt;ul&gt;
        ///&lt;li&gt;Choose SD if you &lt;em&gt;strongly disagree&lt;/em&gt; with the statement.&lt;/li&gt;
        ///&lt;li&gt;Choose D if you &lt;em&gt;disagree&lt;/em&gt; with the statement.&lt;/li&gt;
        ///&lt;li&gt;Choose NS if you are &lt;em&gt;not sure&lt;/em&gt; how you feel about the statement.&lt;/li&gt;
        ///&lt;li&gt;Choose A if you &lt;em&gt;agree&lt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PSIDescription {
            get {
                return ResourceManager.GetString("PSIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSI-4.
        /// </summary>
        public static string PSIQuestionnaireTitle {
            get {
                return ResourceManager.GetString("PSIQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This scale is designed to measure self esteem. Answer each question by placing a number beside the item that best describes how much you agree or disagree with each one as follows:
        ///&lt;ol&gt;
        ///&lt;li&gt;Strongly Agree&lt;/li&gt;
        ///&lt;li&gt;Agree&lt;/li&gt;
        ///&lt;li&gt;Disagree&lt;/li&gt;
        ///&lt;li&gt;Strongly Disagree&lt;/li&gt;
        ///&lt;/ol&gt;.
        /// </summary>
        public static string RSEDescription {
            get {
                return ResourceManager.GetString("RSEDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rosenberg Self Esteem Scale (RSE).
        /// </summary>
        public static string RSEQuestionnaireTitle {
            get {
                return ResourceManager.GetString("RSEQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;If you are &lt;strong&gt;still in contact, please complete&lt;/strong&gt; the rest of this booklet about your relationship with this person &lt;strong&gt;over the past 3 months&lt;/strong&gt;.&lt;/p&gt;
        ///&lt;p&gt;If you are no longer in contact, &lt;strong&gt;please do not complete&lt;/strong&gt; the rest of this booklet.&lt;/p&gt;.
        /// </summary>
        public static string RSFVPDescription {
            get {
                return ResourceManager.GetString("RSFVPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationship Scales.
        /// </summary>
        public static string RSFVPQuestionnaireTitle {
            get {
                return ResourceManager.GetString("RSFVPQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the answer that best applies to you..
        /// </summary>
        public static string SDTDescription {
            get {
                return ResourceManager.GetString("SDTDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marlow Crowne (SDT).
        /// </summary>
        public static string SDTQuestionnaireTitle {
            get {
                return ResourceManager.GetString("SDTQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one test.
        /// </summary>
        public static string SelectTestError {
            get {
                return ResourceManager.GetString("SelectTestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This questionnaire cites statements about your personal attitudes and traits. Read each statement and decide how it describes you. There are no right or wrong answers. Please be truthful and describe yourself as you really are, not as you would like to be.
        ///&lt;ol type=&quot;A&quot;&gt;
        ///&lt;li&gt;Disagree strongly&lt;/li&gt;
        ///&lt;li&gt;Disagree moderately&lt;/li&gt;
        ///&lt;li&gt;Neither agree nor disagree&lt;/li&gt;
        ///&lt;li&gt;Agree moderately&lt;/li&gt;
        ///&lt;li&gt;Agree strongly&lt;/li&gt;
        ///&lt;/ol&gt;.
        /// </summary>
        public static string SESDescription {
            get {
                return ResourceManager.GetString("SESDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Efficiency Scale.
        /// </summary>
        public static string SESQuestionnaireTitle {
            get {
                return ResourceManager.GetString("SESQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This questionnaire contains 112 statements. Read each statement carefully. Please focus on the adolescent you are currently concerned about, and choose the response which best represents your opinion.&lt;/p&gt;
        ///&lt;p&gt;For statements 1-90:
        ///&lt;ul&gt;
        ///&lt;li&gt;Choose SD if you &lt;em&gt;strongly disagree&lt;/em&gt; with the statement.&lt;/li&gt;
        ///&lt;li&gt;Choose D if you &lt;em&gt;disagree&lt;/em&gt; with the statement.&lt;/li&gt;
        ///&lt;li&gt;Choose NS if you are &lt;em&gt;not sure&lt;/em&gt; how you feel about the statement.&lt;/li&gt;
        ///&lt;li&gt;Choose A if you &lt;em&gt;agree&lt;/em&gt; with the stateme [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SIPADescription {
            get {
                return ResourceManager.GetString("SIPADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIPA.
        /// </summary>
        public static string SIPAQuestionnaireTitle {
            get {
                return ResourceManager.GetString("SIPAQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somewhat Agree.
        /// </summary>
        public static string SRSAnswerAgreeSomewhatWithLeft {
            get {
                return ResourceManager.GetString("SRSAnswerAgreeSomewhatWithLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somewhat Agree.
        /// </summary>
        public static string SRSAnswerAgreeSomewhatWithRight {
            get {
                return ResourceManager.GetString("SRSAnswerAgreeSomewhatWithRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree with this side.
        /// </summary>
        public static string SRSAnswerAgreeWithLeft {
            get {
                return ResourceManager.GetString("SRSAnswerAgreeWithLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree with this side.
        /// </summary>
        public static string SRSAnswerAgreeWithRight {
            get {
                return ResourceManager.GetString("SRSAnswerAgreeWithRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string SRSAnswerNeutral {
            get {
                return ResourceManager.GetString("SRSAnswerNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate today&apos;s session according to the following descriptions. Check the square that best describes your reaction using the following rating system..
        /// </summary>
        public static string SRSDescription {
            get {
                return ResourceManager.GetString("SRSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hope.
        /// </summary>
        public static string SRSQuestion10Heading {
            get {
                return ResourceManager.GetString("SRSQuestion10Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I felt hopeful after the session.
        /// </summary>
        public static string SRSQuestion10Left {
            get {
                return ResourceManager.GetString("SRSQuestion10Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I felt hopeless after the session.
        /// </summary>
        public static string SRSQuestion10Right {
            get {
                return ResourceManager.GetString("SRSQuestion10Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance.
        /// </summary>
        public static string SRSQuestion1Heading {
            get {
                return ResourceManager.GetString("SRSQuestion1Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I felt accepted.
        /// </summary>
        public static string SRSQuestion1Left {
            get {
                return ResourceManager.GetString("SRSQuestion1Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I felt criticized or judged.
        /// </summary>
        public static string SRSQuestion1Right {
            get {
                return ResourceManager.GetString("SRSQuestion1Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respect.
        /// </summary>
        public static string SRSQuestion2Heading {
            get {
                return ResourceManager.GetString("SRSQuestion2Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I felt my therapist was respectful.
        /// </summary>
        public static string SRSQuestion2Left {
            get {
                return ResourceManager.GetString("SRSQuestion2Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The therapist pretended to respect or seemed not to respect me.
        /// </summary>
        public static string SRSQuestion2Right {
            get {
                return ResourceManager.GetString("SRSQuestion2Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understanding.
        /// </summary>
        public static string SRSQuestion3Heading {
            get {
                return ResourceManager.GetString("SRSQuestion3Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My therapist understood me and my feelings.
        /// </summary>
        public static string SRSQuestion3Left {
            get {
                return ResourceManager.GetString("SRSQuestion3Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My therapist did not understand my feelings.
        /// </summary>
        public static string SRSQuestion3Right {
            get {
                return ResourceManager.GetString("SRSQuestion3Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honesty and Sincerity.
        /// </summary>
        public static string SRSQuestion4Heading {
            get {
                return ResourceManager.GetString("SRSQuestion4Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We worked on my goals; my goals were important.
        /// </summary>
        public static string SRSQuestion4Left {
            get {
                return ResourceManager.GetString("SRSQuestion4Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My therapist was not sincere, was pretending.
        /// </summary>
        public static string SRSQuestion4Right {
            get {
                return ResourceManager.GetString("SRSQuestion4Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement on Goals.
        /// </summary>
        public static string SRSQuestion5Heading {
            get {
                return ResourceManager.GetString("SRSQuestion5Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My therapist was honest and sincere.
        /// </summary>
        public static string SRSQuestion5Left {
            get {
                return ResourceManager.GetString("SRSQuestion5Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We worked on my therapist&apos;s goals; my goals didn&apos;t seem important.
        /// </summary>
        public static string SRSQuestion5Right {
            get {
                return ResourceManager.GetString("SRSQuestion5Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement on Tasks.
        /// </summary>
        public static string SRSQuestion6Heading {
            get {
                return ResourceManager.GetString("SRSQuestion6Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I approve of the things we did in the session or what I was asked to do as a homework assignment.
        /// </summary>
        public static string SRSQuestion6Left {
            get {
                return ResourceManager.GetString("SRSQuestion6Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t like what we did in today&apos;s session or what I was asked to do as a homework assignment.
        /// </summary>
        public static string SRSQuestion6Right {
            get {
                return ResourceManager.GetString("SRSQuestion6Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement on Treatment.
        /// </summary>
        public static string SRSQuestion7Heading {
            get {
                return ResourceManager.GetString("SRSQuestion7Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The treatment I received was right for me.
        /// </summary>
        public static string SRSQuestion7Left {
            get {
                return ResourceManager.GetString("SRSQuestion7Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was something wrong with the treatment I received.
        /// </summary>
        public static string SRSQuestion7Right {
            get {
                return ResourceManager.GetString("SRSQuestion7Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideas about Change.
        /// </summary>
        public static string SRSQuestion8Heading {
            get {
                return ResourceManager.GetString("SRSQuestion8Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ideas about change were important and a focus of the session.
        /// </summary>
        public static string SRSQuestion8Left {
            get {
                return ResourceManager.GetString("SRSQuestion8Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ideas were not important.
        /// </summary>
        public static string SRSQuestion8Right {
            get {
                return ResourceManager.GetString("SRSQuestion8Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpfulness, Usefulness.
        /// </summary>
        public static string SRSQuestion9Heading {
            get {
                return ResourceManager.GetString("SRSQuestion9Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I found the session helpful.
        /// </summary>
        public static string SRSQuestion9Left {
            get {
                return ResourceManager.GetString("SRSQuestion9Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session was not helpful.
        /// </summary>
        public static string SRSQuestion9Right {
            get {
                return ResourceManager.GetString("SRSQuestion9Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Rating Scale.
        /// </summary>
        public static string SRSQuestionnaireTitle {
            get {
                return ResourceManager.GetString("SRSQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        public static string Tbl_Agree {
            get {
                return ResourceManager.GetString("Tbl_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of the Time.
        /// </summary>
        public static string Tbl_AllOfTheTime {
            get {
                return ResourceManager.GetString("Tbl_AllOfTheTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost Always.
        /// </summary>
        public static string Tbl_AlmostAlways {
            get {
                return ResourceManager.GetString("Tbl_AlmostAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        public static string Tbl_Disagree {
            get {
                return ResourceManager.GetString("Tbl_Disagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently.
        /// </summary>
        public static string Tbl_Frequently {
            get {
                return ResourceManager.GetString("Tbl_Frequently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Good Part of the Time.
        /// </summary>
        public static string Tbl_GoodPartOfTheTime {
            get {
                return ResourceManager.GetString("Tbl_GoodPartOfTheTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Little of the Time.
        /// </summary>
        public static string Tbl_LittleOfTheTime {
            get {
                return ResourceManager.GetString("Tbl_LittleOfTheTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most of the Time.
        /// </summary>
        public static string Tbl_MostOfTheTime {
            get {
                return ResourceManager.GetString("Tbl_MostOfTheTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Tbl_Never {
            get {
                return ResourceManager.GetString("Tbl_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Tbl_No {
            get {
                return ResourceManager.GetString("Tbl_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None of the Time.
        /// </summary>
        public static string Tbl_NoneOfTheTime {
            get {
                return ResourceManager.GetString("Tbl_NoneOfTheTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Opinion.
        /// </summary>
        public static string Tbl_NoOpinion {
            get {
                return ResourceManager.GetString("Tbl_NoOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarely.
        /// </summary>
        public static string Tbl_Rarely {
            get {
                return ResourceManager.GetString("Tbl_Rarely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the Time.
        /// </summary>
        public static string Tbl_SomeOfTheTime {
            get {
                return ResourceManager.GetString("Tbl_SomeOfTheTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes.
        /// </summary>
        public static string Tbl_Sometimes {
            get {
                return ResourceManager.GetString("Tbl_Sometimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongly Agree.
        /// </summary>
        public static string Tbl_StronglyAgree {
            get {
                return ResourceManager.GetString("Tbl_StronglyAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongly Disagree.
        /// </summary>
        public static string Tbl_StronglyDisagree {
            get {
                return ResourceManager.GetString("Tbl_StronglyDisagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Rarely.
        /// </summary>
        public static string Tbl_VeryRarely {
            get {
                return ResourceManager.GetString("Tbl_VeryRarely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Tbl_Yes {
            get {
                return ResourceManager.GetString("Tbl_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following are a list of issues that many people experience. How often have you experienced each of the following in the last &lt;strong&gt;TWO MONTHS&lt;/strong&gt;?.
        /// </summary>
        public static string TSCLDescription {
            get {
                return ResourceManager.GetString("TSCLDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trauma Symptom Check List-40 (TSCL-40).
        /// </summary>
        public static string TSCLQuestionnaireTitle {
            get {
                return ResourceManager.GetString("TSCLQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When answering the questions below, think about the problem you have come to the Centre to work through. Please indicate how much you disagree or agree with each of the following statements. Base your responses on how you are feeling and acting NOW..
        /// </summary>
        public static string UricaDescription {
            get {
                return ResourceManager.GetString("UricaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This survey asks a lot of questions about violence. By &quot;violence&quot;, we mean physical aggression toward a partner or ex-partner, like a wife or girlfriend. This includes throwing objects, pushing, slapping, kicking, or choking, using a weapon, and other behaviors that can cause fear, pain, or injury.&lt;/p&gt;
        ///&lt;p&gt;If you did none of these things, think about &quot;violence&quot; as the thing you did that got you arrested or got you into a domestic violence program.&lt;/p&gt;
        ///&lt;p&gt;By &quot;ending the violence&quot;, we mean using healthy s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string UricaDVDescription {
            get {
                return ResourceManager.GetString("UricaDVDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URICA - DV (2).
        /// </summary>
        public static string UricaDVQuestionnaireTitle {
            get {
                return ResourceManager.GetString("UricaDVQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URICA.
        /// </summary>
        public static string UricaQuestionnaireTitle {
            get {
                return ResourceManager.GetString("UricaQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y-OQ® 2.01 is designed to describe a wide range of troublesome situations, behaviors, and moods that are common in children and adolescents. You may discover that some of the items do not apply to your child’s current situation. If so, &lt;strong&gt;please do not leave these items blank&lt;/strong&gt; but check the “Never or almost never” category. When you begin the Y-OQ® 2.01 you will see that you can easily make your child look as healthy or unhealthy as you wish. &lt;strong&gt;Please do not do that.&lt;/strong&gt; If you a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YOQPDescription {
            get {
                return ResourceManager.GetString("YOQPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Outcome Questionnaire (Parent).
        /// </summary>
        public static string YOQPTitle {
            get {
                return ResourceManager.GetString("YOQPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y-OQ® -SR 2.0 is designed to describe a wide range of troublesome situations, behaviors, and moods that are common in children and adolescents. You may discover that some of the items do not apply to your situation. If so, &lt;strong&gt;please do not leave these items blank&lt;/strong&gt; but check the “Never or almost never” category. When you begin the Y-OQ® -SR 2.0 you will see that you can easily make yourself look as healthy or unhealthy as you wish. &lt;strong&gt;Please do not do that.&lt;/strong&gt; If you are as accura [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YOQSRDescription {
            get {
                return ResourceManager.GetString("YOQSRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Outcome Questionnaire - Self Report.
        /// </summary>
        public static string YOQSRTitle {
            get {
                return ResourceManager.GetString("YOQSRTitle", resourceCulture);
            }
        }
    }
}
