//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Resources.Test.Views {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Resources.Test.Views.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you were growing up, during your first 18 years of life:.
        /// </summary>
        public static string ACEDescription {
            get {
                return ResourceManager.GetString("ACEDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s my ACE Score?.
        /// </summary>
        public static string ACEQuestionnaireTitle {
            get {
                return ResourceManager.GetString("ACEQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string BtnFinish {
            get {
                return ResourceManager.GetString("BtnFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string BtnNext {
            get {
                return ResourceManager.GetString("BtnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Chart.
        /// </summary>
        public static string BtnOpenChart {
            get {
                return ResourceManager.GetString("BtnOpenChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Looking back over the last week&lt;/strong&gt;, help us understand how you have been feeling. Read each item carefully and mark the box which best describes your current situation..
        /// </summary>
        public static string OQDescription {
            get {
                return ResourceManager.GetString("OQDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome Questionnaire (OQ - 45.2).
        /// </summary>
        public static string OutcomeQuestionnaireTitle {
            get {
                return ResourceManager.GetString("OutcomeQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for completing your questionnaires.  Please click the &quot;finish&quot; button below to complete the process.  Once you are done, please return the device to the front desk. .
        /// </summary>
        public static string PageDescriptionResponseComplete {
            get {
                return ResourceManager.GetString("PageDescriptionResponseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your counsellor or the front desk staff should have informed you what questionnaires you should complete before your counselling session today.  If you are unsure, please contact the front desk for assistance.  .
        /// </summary>
        public static string PageDescriptionSelectTest {
            get {
                return ResourceManager.GetString("PageDescriptionSelectTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Test.
        /// </summary>
        public static string PageTitleCompleteTest {
            get {
                return ResourceManager.GetString("PageTitleCompleteTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response Complete.
        /// </summary>
        public static string PageTitleResponseComplete {
            get {
                return ResourceManager.GetString("PageTitleResponseComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Questionnaires.
        /// </summary>
        public static string PageTitleSelectTest {
            get {
                return ResourceManager.GetString("PageTitleSelectTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select at least one test.
        /// </summary>
        public static string SelectTestError {
            get {
                return ResourceManager.GetString("SelectTestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somewhat Agree.
        /// </summary>
        public static string SRSAnswerAgreeSomewhatWithLeft {
            get {
                return ResourceManager.GetString("SRSAnswerAgreeSomewhatWithLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somewhat Agree.
        /// </summary>
        public static string SRSAnswerAgreeSomewhatWithRight {
            get {
                return ResourceManager.GetString("SRSAnswerAgreeSomewhatWithRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree with this side.
        /// </summary>
        public static string SRSAnswerAgreeWithLeft {
            get {
                return ResourceManager.GetString("SRSAnswerAgreeWithLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree with this side.
        /// </summary>
        public static string SRSAnswerAgreeWithRight {
            get {
                return ResourceManager.GetString("SRSAnswerAgreeWithRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral.
        /// </summary>
        public static string SRSAnswerNeutral {
            get {
                return ResourceManager.GetString("SRSAnswerNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please rate today&apos;s session according to the following descriptions. Check the square that best describes your reaction using the following rating system..
        /// </summary>
        public static string SRSDescription {
            get {
                return ResourceManager.GetString("SRSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hope.
        /// </summary>
        public static string SRSQuestion10Heading {
            get {
                return ResourceManager.GetString("SRSQuestion10Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I felt hopeful after the session.
        /// </summary>
        public static string SRSQuestion10Left {
            get {
                return ResourceManager.GetString("SRSQuestion10Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I felt hopeless after the session.
        /// </summary>
        public static string SRSQuestion10Right {
            get {
                return ResourceManager.GetString("SRSQuestion10Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acceptance.
        /// </summary>
        public static string SRSQuestion1Heading {
            get {
                return ResourceManager.GetString("SRSQuestion1Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I felt accepted.
        /// </summary>
        public static string SRSQuestion1Left {
            get {
                return ResourceManager.GetString("SRSQuestion1Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I felt criticized or judged.
        /// </summary>
        public static string SRSQuestion1Right {
            get {
                return ResourceManager.GetString("SRSQuestion1Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Respect.
        /// </summary>
        public static string SRSQuestion2Heading {
            get {
                return ResourceManager.GetString("SRSQuestion2Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I felt my therapist was respectful.
        /// </summary>
        public static string SRSQuestion2Left {
            get {
                return ResourceManager.GetString("SRSQuestion2Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The therapist pretended to respect or seemed not to respect me.
        /// </summary>
        public static string SRSQuestion2Right {
            get {
                return ResourceManager.GetString("SRSQuestion2Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Understanding.
        /// </summary>
        public static string SRSQuestion3Heading {
            get {
                return ResourceManager.GetString("SRSQuestion3Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My therapist understood me and my feelings.
        /// </summary>
        public static string SRSQuestion3Left {
            get {
                return ResourceManager.GetString("SRSQuestion3Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My therapist did not understand my feelings.
        /// </summary>
        public static string SRSQuestion3Right {
            get {
                return ResourceManager.GetString("SRSQuestion3Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honesty and Sincerity.
        /// </summary>
        public static string SRSQuestion4Heading {
            get {
                return ResourceManager.GetString("SRSQuestion4Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We worked on my goals; my goals were important.
        /// </summary>
        public static string SRSQuestion4Left {
            get {
                return ResourceManager.GetString("SRSQuestion4Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My therapist was not sincere, was pretending.
        /// </summary>
        public static string SRSQuestion4Right {
            get {
                return ResourceManager.GetString("SRSQuestion4Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement on Goals.
        /// </summary>
        public static string SRSQuestion5Heading {
            get {
                return ResourceManager.GetString("SRSQuestion5Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My therapist was honest and sincere.
        /// </summary>
        public static string SRSQuestion5Left {
            get {
                return ResourceManager.GetString("SRSQuestion5Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We worked on my therapist&apos;s goals; my goals didn&apos;t seem important.
        /// </summary>
        public static string SRSQuestion5Right {
            get {
                return ResourceManager.GetString("SRSQuestion5Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement on Tasks.
        /// </summary>
        public static string SRSQuestion6Heading {
            get {
                return ResourceManager.GetString("SRSQuestion6Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I approve of the things we did in the session or what I was asked to do as a homework assignment.
        /// </summary>
        public static string SRSQuestion6Left {
            get {
                return ResourceManager.GetString("SRSQuestion6Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I didn&apos;t like what we did in today&apos;s session or what I was asked to do as a homework assignment.
        /// </summary>
        public static string SRSQuestion6Right {
            get {
                return ResourceManager.GetString("SRSQuestion6Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement on Treatment.
        /// </summary>
        public static string SRSQuestion7Heading {
            get {
                return ResourceManager.GetString("SRSQuestion7Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The treatment I received was right for me.
        /// </summary>
        public static string SRSQuestion7Left {
            get {
                return ResourceManager.GetString("SRSQuestion7Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was something wrong with the treatment I received.
        /// </summary>
        public static string SRSQuestion7Right {
            get {
                return ResourceManager.GetString("SRSQuestion7Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideas about Change.
        /// </summary>
        public static string SRSQuestion8Heading {
            get {
                return ResourceManager.GetString("SRSQuestion8Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ideas about change were important and a focus of the session.
        /// </summary>
        public static string SRSQuestion8Left {
            get {
                return ResourceManager.GetString("SRSQuestion8Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ideas were not important.
        /// </summary>
        public static string SRSQuestion8Right {
            get {
                return ResourceManager.GetString("SRSQuestion8Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helpfulness, Usefulness.
        /// </summary>
        public static string SRSQuestion9Heading {
            get {
                return ResourceManager.GetString("SRSQuestion9Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I found the session helpful.
        /// </summary>
        public static string SRSQuestion9Left {
            get {
                return ResourceManager.GetString("SRSQuestion9Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The session was not helpful.
        /// </summary>
        public static string SRSQuestion9Right {
            get {
                return ResourceManager.GetString("SRSQuestion9Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session Rating Scale.
        /// </summary>
        public static string SRSQuestionnaireTitle {
            get {
                return ResourceManager.GetString("SRSQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agree.
        /// </summary>
        public static string Tbl_Agree {
            get {
                return ResourceManager.GetString("Tbl_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Almost Always.
        /// </summary>
        public static string Tbl_AlmostAlways {
            get {
                return ResourceManager.GetString("Tbl_AlmostAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disagree.
        /// </summary>
        public static string Tbl_Disagree {
            get {
                return ResourceManager.GetString("Tbl_Disagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently.
        /// </summary>
        public static string Tbl_Frequently {
            get {
                return ResourceManager.GetString("Tbl_Frequently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Tbl_Never {
            get {
                return ResourceManager.GetString("Tbl_Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string Tbl_No {
            get {
                return ResourceManager.GetString("Tbl_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Opinion.
        /// </summary>
        public static string Tbl_NoOpinion {
            get {
                return ResourceManager.GetString("Tbl_NoOpinion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rarely.
        /// </summary>
        public static string Tbl_Rarely {
            get {
                return ResourceManager.GetString("Tbl_Rarely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sometimes.
        /// </summary>
        public static string Tbl_Sometimes {
            get {
                return ResourceManager.GetString("Tbl_Sometimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongly Agree.
        /// </summary>
        public static string Tbl_StronglyAgree {
            get {
                return ResourceManager.GetString("Tbl_StronglyAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strongly Disagree.
        /// </summary>
        public static string Tbl_StronglyDisagree {
            get {
                return ResourceManager.GetString("Tbl_StronglyDisagree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Tbl_Yes {
            get {
                return ResourceManager.GetString("Tbl_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When answering the questions below, think about the problem you have come to the Centre to work through. Please indicate how much you disagree or agree with each of the following statements. Base your responses on how you are feeling and acting NOW..
        /// </summary>
        public static string UricaDescription {
            get {
                return ResourceManager.GetString("UricaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URICA.
        /// </summary>
        public static string UricaQuestionnaireTitle {
            get {
                return ResourceManager.GetString("UricaQuestionnaireTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y-OQ® 2.01 is designed to describe a wide range of troublesome situations, behaviors, and moods that are common in children and adolescents. You may discover that some of the items do not apply to your child’s current situation. If so, &lt;strong&gt;please do not leave these items blank&lt;/strong&gt; but check the “Never or almost never” category. When you begin the Y-OQ® 2.01 you will see that you can easily make your child look as healthy or unhealthy as you wish. &lt;strong&gt;Please do not do that.&lt;/strong&gt; If you a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YOQPDescription {
            get {
                return ResourceManager.GetString("YOQPDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Outcome Questionnaire (Parent).
        /// </summary>
        public static string YOQPTitle {
            get {
                return ResourceManager.GetString("YOQPTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Y-OQ® -SR 2.0 is designed to describe a wide range of troublesome situations, behaviors, and moods that are common in children and adolescents. You may discover that some of the items do not apply to your situation. If so, &lt;strong&gt;please do not leave these items blank&lt;/strong&gt; but check the “Never or almost never” category. When you begin the Y-OQ® -SR 2.0 you will see that you can easily make yourself look as healthy or unhealthy as you wish. &lt;strong&gt;Please do not do that.&lt;/strong&gt; If you are as accura [rest of string was truncated]&quot;;.
        /// </summary>
        public static string YOQSRDescription {
            get {
                return ResourceManager.GetString("YOQSRDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youth Outcome Questionnaire - Self Report.
        /// </summary>
        public static string YOQSRTitle {
            get {
                return ResourceManager.GetString("YOQSRTitle", resourceCulture);
            }
        }
    }
}
